### ISSUE TITLE
Issue with search filters

### ISSUE THREAD

**Issue by EchterAlsFake** [Egsagon/PHUB#19]
Hi,

I don't know if I just didn't understand how to use the search filters, but when using them I got this error:

```
Traceback (most recent call last):
  File "/home/asuna/PycharmProjects/Porn_Fetch/Porn_Fetch.py", line 626, in search_videos
    query_object = self.client.search(query, locals.Category.ASIAN + locals.Production.PROFESSIONAL + self.sort + self.sort_time - self.excluded_categories_filter)
                                             ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'Param' and 'Param'
```

**Comment by Egsagon** [comment]
Hi,
Thought it was more pythonic to use the `|` operand instead of `+`. Yes, i like to make changes that are absolutely not nescessary and that breaks everything.

**Comment by EchterAlsFake** [comment]
Okay, so that worked now, except for excluding categories.

When using the - operator I got an Assertion Error:

``` 
Traceback (most recent call last):
  File "/home/asuna/PycharmProjects/Porn_Fetch/Porn_Fetch.py", line 630, in search_videos
    query_object = self.client.search(query, self.selected_category | self.production | self.sort | self.sort_time - self.excluded_categories_filter)
                                                                                                    ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "/home/asuna/PycharmProjects/Porn_Fetch/venv/lib/python3.11/site-packages/phub/objects/param.py", line 87, in __sub__
    assert isinstance(other, Param)
AssertionError
``` 

When not Excluding it, I successfully got a Search query object, and the results were pretty accurate to the filters.

**Comment by Egsagon** [comment]
This assertion is there to prevent concatenation with objects that are not Param objects. I should have documented that.
Make sure `self.sort_time` and/or `self.excluded_categories_filter` are `Param` instances.

Also, as i said, i haven't fully implemented the `sort` params. Only some params should accept a sort time: `VIDEO_MOST_VIEWS` and `VIDEO_TOP_RATED`:
```python
# Fetch the videos with the most views, weekly in the given category
query = c.search('cum',
                 (Category.ASIAN
                  |- Category.BBW
                  | Production.HOMEMADE
                  | Sort.VIDEO_MOST_VIEWS # or VIDEO_TOP_RATED
                  | Sort.WEEKLY))
```
The other ones should not even have a sort time parameter. I'll implement this this evening, i just don't know yet if it should throw an error or just ignore the param.

Also note that you can specify which query to use when initialising a query, using the `feature` argument.
`JQuery` is faster and more reliable, but `HQuery` provides results that are more accurate to the website. Both use different parameter key, which is why i could not just make simple constants.
```python
# Fetch the longuest video of all times for this query
query = c.search('cum',
                 Sort.VIDEO_LONGUEST,
                 feature = phub.HQuery)

print(query[0].duration) # Longuest video ever for this query (7 hours when i checked wtf)
```

**Comment by EchterAlsFake** [comment]
Ah okay, thanks for clarifying :)

**Comment by Egsagon** [comment]
Done :)
You should now be able to do:
```python
Sort.VIDEO_TOP_RATED | Sort.DAYLY # or any other sort period
Sort.VIDEO_MOST_VIEWS | Sort.DAYLY
```
But things like:
```python
Sort.LONGUEST | Sort.DAYLY
```
Raises `phub.errors.InvalidSortParam`.

I also added more assertion details and fixed a bug that would prevent categories from being reversed.
Have a good day!
